# Generated by Django 4.0.3 on 2022-03-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_driver_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSLots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_slot_no', models.BigIntegerField()),
                ('parking_slot_available', models.BooleanField(default=True)),
            ],
        ),
    ]
