# Generated by Django 4.0.3 on 2022-04-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_basemodel_event_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_id',
        ),
    ]
